### ISSUE TITLE
Use semi-implicit Euler

### ISSUE THREAD

**Issue by tkoolen** [rdeits/LCPSim.jl#2]
Stewart and Trinkle actually evaluate the mass matrix and dynamics bias term at `q[n] + h * qd[n]` and `v[n]` (semi-implicit Euler), instead of at `q[n]` and `v[n]` (forward Euler). Semi-implicit Euler should give better results than forward Euler in terms of conservation of energy.  It's an easy win, and I don't think you're currently doing this, right?

**Comment by rdeits** [comment]
Yup, right on all counts. I was actually just about to open an issue to remind myself to do this 🙂
